const classes = {
    'black-90': { color: 'rgba( 0, 0, 0, .9 )' },
    'black-80': { color: 'rgba( 0, 0, 0, .8 )' },
    'black-70': { color: 'rgba( 0, 0, 0, .7 )' },
    'black-60': { color: 'rgba( 0, 0, 0, .6 )' },
    'black-50': { color: 'rgba( 0, 0, 0, .5 )' },
    'black-40': { color: 'rgba( 0, 0, 0, .4 )' },
    'black-30': { color: 'rgba( 0, 0, 0, .3 )' },
    'black-20': { color: 'rgba( 0, 0, 0, .2 )' },
    'black-10': { color: 'rgba( 0, 0, 0, .1 )' },
    'black-05': { color: 'rgba( 0, 0, 0, .05 )' },
    'white-90': { color: 'rgba( 255, 255, 255, .9 )' },
    'white-80': { color: 'rgba( 255, 255, 255, .8 )' },
    'white-70': { color: 'rgba( 255, 255, 255, .7 )' },
    'white-60': { color: 'rgba( 255, 255, 255, .6 )' },
    'white-50': { color: 'rgba( 255, 255, 255, .5 )' },
    'white-40': { color: 'rgba( 255, 255, 255, .4 )' },
    'white-30': { color: 'rgba( 255, 255, 255, .3 )' },
    'white-20': { color: 'rgba( 255, 255, 255, .2 )' },
    'white-10': { color: 'rgba( 255, 255, 255, .1 )' },
    black: { color: '#000' },
    'near-black': { color: '#111' },
    'dark-gray': { color: '#333' },
    'mid-gray': { color: '#555' },
    gray: { color: '#777' },
    silver: { color: '#999' },
    'light-silver': { color: '#aaa' },
    'moon-gray': { color: '#ccc' },
    'light-gray': { color: '#eee' },
    'near-white': { color: '#f4f4f4' },
    white: { color: '#fff' },
    'dark-red': { color: '#e7040f' },
    red: { color: '#ff4136' },
    'light-red': { color: '#ff725c' },
    orange: { color: '#ff6300' },
    gold: { color: '#ffb700' },
    yellow: { color: '#ffd700' },
    'light-yellow': { color: '#fbf1a9' },
    purple: { color: '#5e2ca5' },
    'light-purple': { color: '#a463f2' },
    'dark-pink': { color: '#d5008f' },
    'hot-pink': { color: '#ff41b4' },
    pink: { color: '#ff80cc' },
    'light-pink': { color: '#ffa3d7' },
    'dark-green': { color: '#137752' },
    green: { color: '#19a974' },
    'light-green': { color: '#9eebcf' },
    navy: { color: '#001b44' },
    'dark-blue': { color: '#00449e' },
    blue: { color: '#357edd' },
    'light-blue': { color: '#96ccff' },
    'lightest-blue': { color: '#cdecff' },
    'washed-blue': { color: '#f6fffe' },
    'washed-green': { color: '#e8fdf5' },
    'washed-yellow': { color: '#fffceb' },
    'washed-red': { color: '#ffdfdf' },
    'color-inherit': { color: 'inherit' },
    'bg-black-90': { backgroundColor: 'rgba( 0, 0, 0, .9 )' },
    'bg-black-80': { backgroundColor: 'rgba( 0, 0, 0, .8 )' },
    'bg-black-70': { backgroundColor: 'rgba( 0, 0, 0, .7 )' },
    'bg-black-60': { backgroundColor: 'rgba( 0, 0, 0, .6 )' },
    'bg-black-50': { backgroundColor: 'rgba( 0, 0, 0, .5 )' },
    'bg-black-40': { backgroundColor: 'rgba( 0, 0, 0, .4 )' },
    'bg-black-30': { backgroundColor: 'rgba( 0, 0, 0, .3 )' },
    'bg-black-20': { backgroundColor: 'rgba( 0, 0, 0, .2 )' },
    'bg-black-10': { backgroundColor: 'rgba( 0, 0, 0, .1 )' },
    'bg-black-05': { backgroundColor: 'rgba( 0, 0, 0, .05 )' },
    'bg-white-90': { backgroundColor: 'rgba( 255, 255, 255, .9 )' },
    'bg-white-80': { backgroundColor: 'rgba( 255, 255, 255, .8 )' },
    'bg-white-70': { backgroundColor: 'rgba( 255, 255, 255, .7 )' },
    'bg-white-60': { backgroundColor: 'rgba( 255, 255, 255, .6 )' },
    'bg-white-50': { backgroundColor: 'rgba( 255, 255, 255, .5 )' },
    'bg-white-40': { backgroundColor: 'rgba( 255, 255, 255, .4 )' },
    'bg-white-30': { backgroundColor: 'rgba( 255, 255, 255, .3 )' },
    'bg-white-20': { backgroundColor: 'rgba( 255, 255, 255, .2 )' },
    'bg-white-10': { backgroundColor: 'rgba( 255, 255, 255, .1 )' },
    'bg-black': { backgroundColor: '#000' },
    'bg-near-black': { backgroundColor: '#111' },
    'bg-dark-gray': { backgroundColor: '#333' },
    'bg-mid-gray': { backgroundColor: '#555' },
    'bg-gray': { backgroundColor: '#777' },
    'bg-silver': { backgroundColor: '#999' },
    'bg-light-silver': { backgroundColor: '#aaa' },
    'bg-moon-gray': { backgroundColor: '#ccc' },
    'bg-light-gray': { backgroundColor: '#eee' },
    'bg-near-white': { backgroundColor: '#f4f4f4' },
    'bg-white': { backgroundColor: '#fff' },
    'bg-transparent': { backgroundColor: 'transparent' },
    'bg-dark-red': { backgroundColor: '#e7040f' },
    'bg-red': { backgroundColor: '#ff4136' },
    'bg-light-red': { backgroundColor: '#ff725c' },
    'bg-orange': { backgroundColor: '#ff6300' },
    'bg-gold': { backgroundColor: '#ffb700' },
    'bg-yellow': { backgroundColor: '#ffd700' },
    'bg-light-yellow': { backgroundColor: '#fbf1a9' },
    'bg-purple': { backgroundColor: '#5e2ca5' },
    'bg-light-purple': { backgroundColor: '#a463f2' },
    'bg-dark-pink': { backgroundColor: '#d5008f' },
    'bg-hot-pink': { backgroundColor: '#ff41b4' },
    'bg-pink': { backgroundColor: '#ff80cc' },
    'bg-light-pink': { backgroundColor: '#ffa3d7' },
    'bg-dark-green': { backgroundColor: '#137752' },
    'bg-green': { backgroundColor: '#19a974' },
    'bg-light-green': { backgroundColor: '#9eebcf' },
    'bg-navy': { backgroundColor: '#001b44' },
    'bg-dark-blue': { backgroundColor: '#00449e' },
    'bg-blue': { backgroundColor: '#357edd' },
    'bg-light-blue': { backgroundColor: '#96ccff' },
    'bg-lightest-blue': { backgroundColor: '#cdecff' },
    'bg-washed-blue': { backgroundColor: '#f6fffe' },
    'bg-washed-green': { backgroundColor: '#e8fdf5' },
    'bg-washed-yellow': { backgroundColor: '#fffceb' },
    'bg-washed-red': { backgroundColor: '#ffdfdf' },
    'bg-inherit': { backgroundColor: 'inherit' }
};

export default classes;
